language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g bower grunt-cli
  - bower install
 script:  
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls --verbose
services: mongodb